import { InventoryStatus, Tinventory_updated } from "../types/Tinventory.ts";

export const inventoryData: Tinventory_updated[] = [
  {
    id: "a1b2c3d4",
    itemName: "Wireless Gaming Mouse lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    sku: "SKU-2024-MSE",
    stock: 50,
    price: 29.99,
    category: "Electronics",
    status: InventoryStatus.Active,
    expireDate: new Date("2026-07-23"),
  },
  {
    id: "e5f6g7h8",
    itemName: "Ergonomic Office Chair",
    sku: "SKU-2024-CHR",
    stock: 15,
    price: 149.99,
    category: "Furniture",
    status: InventoryStatus.Active,
    expireDate: new Date("2027-01-15"),
  },
  {
    id: "i9j0k1l2",
    itemName: "Smart Blender Pro",
    sku: "SKU-2024-BLD",
    stock: 0,
    price: 89.99,
    category: "Appliances",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2025-12-31"),
  },
  {
    id: "m3n4o5p6",
    itemName: "LED Desk Lamp",
    sku: "SKU-2024-LMP",
    stock: 25,
    price: 39.99,
    category: "Lighting",
    status: InventoryStatus.Active,
    expireDate: new Date("2028-03-10"),
  },
  {
    id: "q7r8s9t0",
    itemName: "Noise-Canceling Headphones",
    sku: "SKU-2024-HPH",
    stock: 8,
    price: 199.99,
    category: "Electronics",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2025-09-20"),
  },
  {
    id: "u1v2w3x4",
    itemName: "Portable Bluetooth Speaker",
    sku: "SKU-2024-SPK",
    stock: 30,
    price: 49.99,
    category: "Electronics",
    status: InventoryStatus.Active,
    expireDate: new Date("2026-11-05"),
  },
  {
    id: "y5z6a7b8",
    itemName: "Adjustable Standing Desk",
    sku: "SKU-2024-DSK",
    stock: 10,
    price: 299.99,
    category: "Furniture",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2027-06-30"),
  },
  {
    id: "c9d0e1f2",
    itemName: "Smart Thermostat",
    sku: "SKU-2024-THM",
    stock: 5,
    price: 129.99,
    category: "Appliances",
    status: InventoryStatus.Active,
    expireDate: new Date("2026-04-18"),
  },
  {
    id: "g3h4i5j6",
    itemName: "Rechargeable Flashlight",
    sku: "SKU-2024-FLS",
    stock: 40,
    price: 19.99,
    category: "Lighting",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2025-08-12"),
  },
  {
    id: "k7l8m9n0",
    itemName: "Wireless Earbuds",
    sku: "SKU-2024-EBD",
    stock: 20,
    price: 99.99,
    category: "Electronics",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2025-10-25"),
  },
  {
    id: "o1p2q3r4",
    itemName: "Electric Kettle",
    sku: "SKU-2024-KTL",
    stock: 18,
    price: 39.99,
    category: "Appliances",
    status: InventoryStatus.Active,
    expireDate: new Date("2026-02-14"),
  },
  {
    id: "s5t6u7v8",
    itemName: "Memory Foam Pillow",
    sku: "SKU-2024-PLW",
    stock: 25,
    price: 29.99,
    category: "Furniture",
    status: InventoryStatus.Active,
    expireDate: new Date("2027-05-22"),
  },
  {
    id: "w9x0y1z2",
    itemName: "Smart LED Bulb",
    sku: "SKU-2024-BLB",
    stock: 60,
    price: 14.99,
    category: "Lighting",
    status: InventoryStatus.Active,
    expireDate: new Date("2028-01-08"),
  },
  {
    id: "a3b4c5d6",
    itemName: "Gaming Keyboard",
    sku: "SKU-2024-KBD",
    stock: 35,
    price: 79.99,
    category: "Electronics",
    status: InventoryStatus.Active,
    expireDate: new Date("2026-09-17"),
  },
  {
    id: "e7f8g9h0",
    itemName: "Air Purifier",
    sku: "SKU-2024-APR",
    stock: 12,
    price: 199.99,
    category: "Appliances",
    status: InventoryStatus.Active,
    expireDate: new Date("2026-12-03"),
  },
  {
    id: "i1j2k3l4",
    itemName: "Wall-Mounted Bookshelf",
    sku: "SKU-2024-BKS",
    stock: 8,
    price: 89.99,
    category: "Furniture",
    status: InventoryStatus.Active,
    expireDate: new Date("2027-08-11"),
  },
  {
    id: "m5n6o7p8",
    itemName: "LED String Lights",
    sku: "SKU-2024-SLT",
    stock: 50,
    price: 24.99,
    category: "Lighting",
    status: InventoryStatus.Active,
    expireDate: new Date("2027-11-28"),
  },
  {
    id: "q9r0s1t2",
    itemName: "Smartwatch",
    sku: "SKU-2024-SMW",
    stock: 15,
    price: 249.99,
    category: "Electronics",
    status: InventoryStatus.Active,
    expireDate: new Date("2026-03-07"),
  },
  {
    id: "u3v4w5x6",
    itemName: "Cordless Vacuum Cleaner",
    sku: "SKU-2024-VCM",
    stock: 10,
    price: 299.99,
    category: "Appliances",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2025-11-15"),
  },
  {
    id: "y7z8a9b0",
    itemName: "Ergonomic Keyboard Tray",
    sku: "SKU-2024-KBT",
    stock: 20,
    price: 59.99,
    category: "Furniture",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2026-05-29"),
  },
  {
    id: "c1d2e3f4",
    itemName: "Portable Power Bank",
    sku: "SKU-2024-PBK",
    stock: 45,
    price: 29.99,
    category: "Electronics",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2025-12-08"),
  },
  {
    id: "g5h6i7j8",
    itemName: "Electric Pressure Cooker",
    sku: "SKU-2024-PRC",
    stock: 7,
    price: 129.99,
    category: "Appliances",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2026-01-20"),
  },
  {
    id: "k9l0m1n2",
    itemName: "Desk Organizer Set",
    sku: "SKU-2024-ORG",
    stock: 30,
    price: 19.99,
    category: "Furniture",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2027-04-13"),
  },
  {
    id: "o3p4q5r6",
    itemName: "Solar-Powered Lantern",
    sku: "SKU-2024-LTN",
    stock: 25,
    price: 34.99,
    category: "Lighting",
    status: InventoryStatus.Inactive,
    expireDate: new Date("2026-10-06"),
  },
];